### ISSUE TITLE
I am not able to install CaesiumCLT in my ubuntu system

### ISSUE THREAD

**Issue by satyagvns** [Lymphatus/CaesiumCLT#1]
Hi Team,

Can you please help to install caesium in linux (ubuntu) machine.

1. git clone from CaesiumCLT to my system.
2. cd CaesiumCLT
3. I followed "INSTALL" file for install in my system
4. Installed "# sudo apt-get install libjpeg-turbo-progs"
5. ./configure

Output:
=======
```
./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for  in -ljpeg... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking sys/stats.h usability... no
checking sys/stats.h presence... no
checking for sys/stats.h... no
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking jpeglib.h usability... no
checking jpeglib.h presence... no
checking for jpeglib.h... no
Cannot find jpeglib.h.

6. # make
make: *** No targets specified and no makefile found.  Stop.
```

I am root in this process.

Cloud you please help me to fix this problem.

Thanks,
Satya

**Comment by Lymphatus** [comment]
Hi Satya,

The last lines of the console give you the error you are looking for. 

    checking jpeglib.h usability... no
    checking jpeglib.h presence... no
    checking for jpeglib.h... no
    Cannot find jpeglib.h.

Here we go. You don't have libjpeg on your system, which is required for CaesiumCLT to work. You need to install it, using the application installer or by typing in console (preferred)

    $ sudo apt-get install libjpeg-dev

Doing this should fix the error. You'll probably get another one similar to this, asking for "turbojpeg.h". I'm not working on a Ubuntu machine, so I didn't test it deeply, but I think you should type

    $ sudo apt-get install libjpeg-turbo8-dev

and you'll be fine.

Note that it is a beta, so it may not work as you expect. For example, I'm getting a lot of errors with input/output folders and I'm working on a fix. Make sure to backup your pictures before testing on them.

Let me know if you have any other issue.

**Comment by satyagvns** [comment]
Hi Team,
I have followed your commands. Bellow  are the errors which I got
# makeMaking all in srcmake[1]: Entering directory `/home/paxterra/CaesiumCLT/src'make[2]: Entering directory `/home/paxterra/CaesiumCLT'make[2]: Leaving directory `/home/paxterra/CaesiumCLT'gcc -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2   -o caesiumclt caesiumclt-main.o caesiumclt-utils.o caesiumclt-lossless.o caesiumclt-compress.o  caesiumclt-utils.o: In function `jcopy_markers_execute':/home/paxterra/CaesiumCLT/src/utils.c:145: undefined reference to `jpeg_write_marker'caesiumclt-lossless.o: In function `cclt_get_markers':/home/paxterra/CaesiumCLT/src/lossless.c:15: undefined reference to `jpeg_std_error'/home/paxterra/CaesiumCLT/src/lossless.c:17: undefined reference to `jpeg_CreateDecompress'/home/paxterra/CaesiumCLT/src/lossless.c:30: undefined reference to `jpeg_stdio_src'/home/paxterra/CaesiumCLT/src/lossless.c:34: undefined reference to `jpeg_save_markers'/home/paxterra/CaesiumCLT/src/lossless.c:37: undefined reference to `jpeg_read_header'caesiumclt-lossless.o: In function `cclt_optimize':/home/paxterra/CaesiumCLT/src/lossless.c:60: undefined reference to `jpeg_std_error'/home/paxterra/CaesiumCLT/src/lossless.c:61: undefined reference to `jpeg_CreateDecompress'/home/paxterra/CaesiumCLT/src/lossless.c:62: undefined reference to `jpeg_std_error'/home/paxterra/CaesiumCLT/src/lossless.c:63: undefined reference to `jpeg_CreateCompress'/home/paxterra/CaesiumCLT/src/lossless.c:76: undefined reference to `jpeg_stdio_src'/home/paxterra/CaesiumCLT/src/lossless.c:86: undefined reference to `jpeg_read_header'/home/paxterra/CaesiumCLT/src/lossless.c:89: undefined reference to `jpeg_read_coefficients'/home/paxterra/CaesiumCLT/src/lossless.c:93: undefined reference to `jpeg_copy_critical_parameters'/home/paxterra/CaesiumCLT/src/lossless.c:113: undefined reference to `jpeg_simple_progression'/home/paxterra/CaesiumCLT/src/lossless.c:116: undefined reference to `jpeg_stdio_dest'/home/paxterra/CaesiumCLT/src/lossless.c:119: undefined reference to `jpeg_write_coefficients'/home/paxterra/CaesiumCLT/src/lossless.c:134: undefined reference to `jpeg_finish_compress'/home/paxterra/CaesiumCLT/src/lossless.c:135: undefined reference to `jpeg_destroy_compress'/home/paxterra/CaesiumCLT/src/lossless.c:136: undefined reference to `jpeg_finish_decompress'/home/paxterra/CaesiumCLT/src/lossless.c:137: undefined reference to `jpeg_destroy_decompress'/home/paxterra/CaesiumCLT/src/lossless.c:81: undefined reference to `jpeg_save_markers'/home/paxterra/CaesiumCLT/src/lossless.c:129: undefined reference to `jpeg_destroy_decompress'caesiumclt-compress.o: In function `cclt_compress':/home/paxterra/CaesiumCLT/src/compress.c:30: undefined reference to `tjInitCompress'/home/paxterra/CaesiumCLT/src/compress.c:32: undefined reference to `tjCompress2'/home/paxterra/CaesiumCLT/src/compress.c:48: undefined reference to `tjDestroy'/home/paxterra/CaesiumCLT/src/compress.c:49: undefined reference to `tjFree'caesiumclt-compress.o: In function `cclt_decompress':/home/paxterra/CaesiumCLT/src/compress.c:67: undefined reference to `tjAlloc'/home/paxterra/CaesiumCLT/src/compress.c:71: undefined reference to `tjInitDecompress'/home/paxterra/CaesiumCLT/src/compress.c:72: undefined reference to `tjDecompressHeader2'/home/paxterra/CaesiumCLT/src/compress.c:74: undefined reference to `ceil'/home/paxterra/CaesiumCLT/src/compress.c:75: undefined reference to `ceil'/home/paxterra/CaesiumCLT/src/compress.c:82: undefined reference to `tjAlloc'/home/paxterra/CaesiumCLT/src/compress.c:84: undefined reference to `tjDecompress2'/home/paxterra/CaesiumCLT/src/compress.c:94: undefined reference to `tjDestroy'collect2: error: ld returned 1 exit statusmake[1]: *** [caesiumclt] Error 1make[1]: Leaving directory `/home/paxterra/CaesiumCLT/src'make: *** [all-recursive] Error 1
Warm Regards,U V N SATYANARAYANA MURTHY,+91 – 872 271 6216.SkypeId : satya_bindu

Date: Thu, 23 Jul 2015 01:12:04 -0700

**Comment by Lymphatus** [comment]
Can you post me the output of these 2 commands?

```
$ lsb_release -a
```
```
$ uname -a
```

**Comment by satyagvns** [comment]
# lsb_release -aNo LSB modules are available.Distributor ID:	UbuntuDescription:	Ubuntu 14.04.1 LTSRelease:	14.04Codename:	trusty

# uname -aLinux mydomain.com 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Warm Regards,U V N SATYANARAYANA MURTHY,+91 – 872 271 6216.SkypeId : satya_bindu

Date: Thu, 23 Jul 2015 01:41:09 -0700

**Comment by Lymphatus** [comment]
Probably missing the libjpeg devel package. Try

```bash
$ sudo apt-get install libjpeg62-dev
```

**Comment by satyagvns** [comment]
Hi,
Thanks for helping me. But unfortunately another error came.
#makeMaking all in srcmake[1]: Entering directory `/home/paxterra/CaesiumCLT/src'make[2]: Entering directory `/home/paxterra/CaesiumCLT'make[2]: Leaving directory `/home/paxterra/CaesiumCLT'gcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -MT caesiumclt-main.o -MD -MP -MF .deps/caesiumclt-main.Tpo -c -o caesiumclt-main.o `test -f 'main.c' || echo './'`main.cIn file included from compress.h:4:0,                 from main.c:12:utils.h:5:23: fatal error: turbojpeg.h: No such file or directory #include <turbojpeg.h>                       ^compilation terminated.make[1]: *** [caesiumclt-main.o] Error 1make[1]: Leaving directory `/home/paxterra/CaesiumCLT/src'make: *** [all-recursive] Error 1
Warm Regards,U V N SATYANARAYANA MURTHY,+91 – 872 271 6216.SkypeId : satya_bindu

Date: Thu, 23 Jul 2015 02:06:17 -0700

**Comment by Lymphatus** [comment]
Checked on my Ubuntu VM. Problems are two: first is an error in the makefile. The second is in the code and won't make you compile anyway. I will commit a fix to the repo and notify you back when it'll be ok. Should be up in a few hours.

**Comment by Lymphatus** [comment]
Came out with a fix. Works on my Ubuntu machine.

Instructions:
- **Get the new version (clone again or push)**
- **Clean previous installed packages to avoid conflicts by typing**
```
$ sudo apt-get autoremove libjpeg62-dev libjpeg-turbo8-dev
```
- **Install again**
```
$ sudo apt-get install libjpeg-turbo8-dev
```
- **Repeat the compilation steps as in INSTALL**
```
$ cd CaesiumCLT
$ ./configure
$ make
$ sudo make install
```

Should compile and install smoothly now. Let me know.

**Comment by satyagvns** [comment]
Hi,
I am following your commands...
@make command. I got bellow error..
 makeCDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/paxterra/CaesiumCLT/tools/missing aclocal-1.15 /home/myhome/CaesiumCLT/tools/missing: line 81: aclocal-1.15: command not foundWARNING: 'aclocal-1.15' is missing on your system.         You should only need it if you modified 'acinclude.m4' or         'configure.ac' or m4 files included by 'configure.ac'.         The 'aclocal' program is part of the GNU Automake package:         <http://www.gnu.org/software/automake>         It also requires GNU Autoconf, GNU m4 and Perl in order to run:         <http://www.gnu.org/software/autoconf>         <http://www.gnu.org/software/m4/>         <http://www.perl.org/>make: *** [aclocal.m4] Error 127
Later I searched this error  in google. I found one command called "autoconf" to be install. I installed and run autoconf command and I ran the "make" command again. I got bellow error.
# make/bin/bash ./config.status --recheckrunning CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursionchecking for a BSD-compatible install... /usr/bin/install -cchecking whether build environment is sane... yeschecking for a thread-safe mkdir -p... /bin/mkdir -pchecking for gawk... gawkchecking whether make sets $(MAKE)... yeschecking whether make supports nested variables... yeschecking for gcc... gccchecking whether the C compiler works... yeschecking for C compiler default output file name... a.outchecking for suffix of executables... checking whether we are cross compiling... nochecking for suffix of object files... ochecking whether we are using the GNU C compiler... yeschecking whether gcc accepts -g... yeschecking for gcc option to accept ISO C89... none neededchecking whether gcc understands -c and -o together... yeschecking for style of include used by make... GNUchecking dependency style of gcc... gcc3checking for  in -ljpeg... nochecking how to run the C preprocessor... gcc -Echecking for grep that handles long lines and -e... /bin/grepchecking for egrep... /bin/grep -Echecking for ANSI C header files... yeschecking for sys/types.h... yeschecking for sys/stat.h... yeschecking for stdlib.h... yeschecking for string.h... yeschecking for memory.h... yeschecking for strings.h... yeschecking for inttypes.h... yeschecking for stdint.h... yeschecking for unistd.h... yeschecking limits.h usability... yeschecking limits.h presence... yeschecking for limits.h... yeschecking for stdlib.h... (cached) yeschecking for string.h... (cached) yeschecking getopt.h usability... yeschecking getopt.h presence... yeschecking for getopt.h... yeschecking stdio.h usability... yeschecking stdio.h presence... yeschecking for stdio.h... yeschecking sys/stats.h usability... nochecking sys/stats.h presence... nochecking for sys/stats.h... nochecking dirent.h usability... yeschecking dirent.h presence... yeschecking for dirent.h... yeschecking jpeglib.h usability... yeschecking jpeglib.h presence... yeschecking for jpeglib.h... yeschecking for off_t... yeschecking for stdlib.h... (cached) yeschecking for GNU libc compatible malloc... yeschecking for mkdir... yeschecking for strrchr... yeschecking for strtol... yeschecking that generated files are newer than configure... doneconfigure: creating ./config.status /bin/bash ./config.statusconfig.status: creating Makefileconfig.status: creating src/Makefileconfig.status: executing depfiles commandsMaking all in srcmake[1]: Entering directory `/home/paxterra/CaesiumCLT/src'gcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -MT caesiumclt-main.o -MD -MP -MF .deps/caesiumclt-main.Tpo -c -o caesiumclt-main.o `test -f 'main.c' || echo './'`main.cmv -f .deps/caesiumclt-main.Tpo .deps/caesiumclt-main.Pogcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -MT caesiumclt-utils.o -MD -MP -MF .deps/caesiumclt-utils.Tpo -c -o caesiumclt-utils.o `test -f 'utils.c' || echo './'`utils.cutils.c: In function ‘scan_folder’:utils.c:234:5: warning: implicit declaration of function ‘chdir’ [-Wimplicit-function-declaration]     chdir(dir);     ^utils.c:236:9: warning: implicit declaration of function ‘lstat’ [-Wimplicit-function-declaration]         lstat(entry->d_name, &statbuf);         ^utils.c:258:5: warning: return from incompatible pointer type [enabled by default]     return *files;     ^mv -f .deps/caesiumclt-utils.Tpo .deps/caesiumclt-utils.Pogcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -MT caesiumclt-lossless.o -MD -MP -MF .deps/caesiumclt-lossless.Tpo -c -o caesiumclt-lossless.o `test -f 'lossless.c' || echo './'`lossless.cmv -f .deps/caesiumclt-lossless.Tpo .deps/caesiumclt-lossless.Pogcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -MT caesiumclt-compress.o -MD -MP -MF .deps/caesiumclt-compress.Tpo -c -o caesiumclt-compress.o `test -f 'compress.c' || echo './'`compress.ccompress.c: In function ‘cclt_compress’:compress.c:17:6: warning: variable ‘status’ set but not used [-Wunused-but-set-variable]  int status;      ^compress.c: In function ‘cclt_decompress’:compress.c:58:9: warning: variable ‘res’ set but not used [-Wunused-but-set-variable]     int res = 0;         ^mv -f .deps/caesiumclt-compress.Tpo .deps/caesiumclt-compress.Pogcc -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2   -o caesiumclt caesiumclt-main.o caesiumclt-utils.o caesiumclt-lossless.o caesiumclt-compress.o  caesiumclt-utils.o: In function `jcopy_markers_execute':/home/paxterra/CaesiumCLT/src/utils.c:145: undefined reference to `jpeg_write_marker'caesiumclt-lossless.o: In function `cclt_get_markers':/home/paxterra/CaesiumCLT/src/lossless.c:15: undefined reference to `jpeg_std_error'/home/paxterra/CaesiumCLT/src/lossless.c:17: undefined reference to `jpeg_CreateDecompress'/home/paxterra/CaesiumCLT/src/lossless.c:30: undefined reference to `jpeg_stdio_src'/home/paxterra/CaesiumCLT/src/lossless.c:34: undefined reference to `jpeg_save_markers'/home/paxterra/CaesiumCLT/src/lossless.c:37: undefined reference to `jpeg_read_header'caesiumclt-lossless.o: In function `cclt_optimize':/home/paxterra/CaesiumCLT/src/lossless.c:60: undefined reference to `jpeg_std_error'/home/paxterra/CaesiumCLT/src/lossless.c:61: undefined reference to `jpeg_CreateDecompress'/home/paxterra/CaesiumCLT/src/lossless.c:62: undefined reference to `jpeg_std_error'/home/paxterra/CaesiumCLT/src/lossless.c:63: undefined reference to `jpeg_CreateCompress'/home/paxterra/CaesiumCLT/src/lossless.c:76: undefined reference to `jpeg_stdio_src'/home/paxterra/CaesiumCLT/src/lossless.c:86: undefined reference to `jpeg_read_header'/home/paxterra/CaesiumCLT/src/lossless.c:89: undefined reference to `jpeg_read_coefficients'/home/paxterra/CaesiumCLT/src/lossless.c:93: undefined reference to `jpeg_copy_critical_parameters'/home/paxterra/CaesiumCLT/src/lossless.c:113: undefined reference to `jpeg_simple_progression'/home/paxterra/CaesiumCLT/src/lossless.c:116: undefined reference to `jpeg_stdio_dest'/home/paxterra/CaesiumCLT/src/lossless.c:119: undefined reference to `jpeg_write_coefficients'/home/paxterra/CaesiumCLT/src/lossless.c:134: undefined reference to `jpeg_finish_compress'/home/paxterra/CaesiumCLT/src/lossless.c:135: undefined reference to `jpeg_destroy_compress'/home/paxterra/CaesiumCLT/src/lossless.c:136: undefined reference to `jpeg_finish_decompress'/home/paxterra/CaesiumCLT/src/lossless.c:137: undefined reference to `jpeg_destroy_decompress'/home/paxterra/CaesiumCLT/src/lossless.c:81: undefined reference to `jpeg_save_markers'/home/paxterra/CaesiumCLT/src/lossless.c:129: undefined reference to `jpeg_destroy_decompress'caesiumclt-compress.o: In function `cclt_compress':/home/paxterra/CaesiumCLT/src/compress.c:30: undefined reference to `tjInitCompress'/home/paxterra/CaesiumCLT/src/compress.c:32: undefined reference to `tjCompress2'/home/paxterra/CaesiumCLT/src/compress.c:48: undefined reference to `tjDestroy'/home/paxterra/CaesiumCLT/src/compress.c:49: undefined reference to `tjFree'caesiumclt-compress.o: In function `cclt_decompress':/home/paxterra/CaesiumCLT/src/compress.c:67: undefined reference to `tjAlloc'/home/paxterra/CaesiumCLT/src/compress.c:71: undefined reference to `tjInitDecompress'/home/paxterra/CaesiumCLT/src/compress.c:72: undefined reference to `tjDecompressHeader2'/home/paxterra/CaesiumCLT/src/compress.c:74: undefined reference to `ceil'/home/paxterra/CaesiumCLT/src/compress.c:75: undefined reference to `ceil'/home/paxterra/CaesiumCLT/src/compress.c:82: undefined reference to `tjAlloc'/home/paxterra/CaesiumCLT/src/compress.c:84: undefined reference to `tjDecompress2'/home/paxterra/CaesiumCLT/src/compress.c:94: undefined reference to `tjDestroy'collect2: error: ld returned 1 exit statusmake[1]: *** [caesiumclt] Error 1make[1]: Leaving directory `/home/paxterra/CaesiumCLT/src'make: *** [all-recursive] Error 1


Warm Regards,U V N SATYANARAYANA MURTHY,+91 – 872 271 6216.SkypeId : satya_bindu

Date: Thu, 23 Jul 2015 06:13:23 -0700

**Comment by Lymphatus** [comment]
Is the file located at
```
src/Makefile.am
```
looking like this?
```
bin_PROGRAMS = caesiumclt
caesiumclt_SOURCES = main.c utils.c lossless.c compress.c
caesiumclt_CFLAGS = -Wall -D_FILE_OFFSET_BITS=64 -std=c99
caesiumclt_LDADD = -ljpeg -lturbojpeg -lm
```

**Comment by satyagvns** [comment]
This is my file structure in CaesiumCLT directory
aclocal.m4  AUTHORS  autom4te.cache  config.log  config.status  configure  configure.ac  COPYING  INSTALL  Makefile  Makefile.am  Makefile.in  README.md  src  tools
src and tools are directories

Warm Regards,U V N SATYANARAYANA MURTHY,+91 – 872 271 6216.SkypeId : satya_bindu

Date: Fri, 24 Jul 2015 00:19:01 -0700

**Comment by Lymphatus** [comment]
Go in the **src** directory and look for **Makefile.am** and paste the content here please.

**Comment by satyagvns** [comment]
src/Makefile.am
bin_PROGRAMS = caesiumcltcaesiumclt_SOURCES = main.c utils.c lossless.c compress.ccaesiumclt_CFLAGS = -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99caesiumclt_OBJCFLAGS = -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm


Warm Regards,U V N SATYANARAYANA MURTHY,+91 – 872 271 6216.SkypeId : satya_bindu

Date: Fri, 24 Jul 2015 00:22:40 -0700

**Comment by Lymphatus** [comment]
That's the problem, you have the old version of it.
Go in the CaesiumCLT folder and type
```
git pull
```
to have the latest changes. If you want, you can also go for a fresh restart by deleting the folder and clone again the repository.
Be sure that the files are up to date and try again with
```bash
$ ./configure
$ make
$ sudo make install
```

**Comment by satyagvns** [comment]
I think I completed installation in my ubuntu.

How to run this tool for my jpeg files?

**Comment by satyagvns** [comment]
# make
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for  in -ljpeg... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking sys/stats.h usability... no
checking sys/stats.h presence... no
checking for sys/stats.h... no
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking jpeglib.h usability... yes
checking jpeglib.h presence... yes
checking for jpeglib.h... yes
checking for off_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for mkdir... yes
checking for strrchr... yes
checking for strtol... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands
Making all in src
make[1]: Entering directory `/home/myhome/CaesiumCLT/src'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/myhome/CaesiumCLT/src'
make[1]: Entering directory `/home/myhome/CaesiumCLT'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/myhome/CaesiumCLT'
root@sib:/home/myhome/CaesiumCLT# make install
Making install in src
make[1]: Entering directory `/home/myhome/CaesiumCLT/src'
make[2]: Entering directory `/home/myhome/CaesiumCLT/src'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c caesiumclt '/usr/local/bin'
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/home/myhome/CaesiumCLT/src'
make[1]: Leaving directory `/home/myhome/CaesiumCLT/src'
make[1]: Entering directory `/home/myhome/CaesiumCLT'
make[2]: Entering directory `/home/myhome/CaesiumCLT'
make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/usr/local/share/doc/caesiumclt'
 /usr/bin/install -c -m 644 README.md '/usr/local/share/doc/caesiumclt'
make[2]: Leaving directory `/home/myhome/CaesiumCLT'
make[1]: Leaving directory `/home/myhome/CaesiumCLT'


Did I install Properly?

**Comment by satyagvns** [comment]
# caesiumclt -hCCLT - Caesium Command Line Tools
Usage: cclt [OPTION] INPUT...Compress your pictures up to 90% without visible quality loss.
Options:	-q	set output file quality between [1-100], ignored for non-JPEGs	-e	keeps EXIF info during compression	-o	compress to custom folder	-l	use lossless optimization	-s	scale to value, expressed as percentage (e.g. 20%)	-R	if input is a folder, scan subfolders too	-h	display this help and exit	-v	output version information and exit
# caesiumclt -l -o test/ satya.jpg Segmentation fault (core dumped)
# cd test/# ls ==> Nothing displayed compressed image.


Warm Regards,U V N SATYANARAYANA MURTHY,+91 – 872 271 6216.SkypeId : satya_bindu

Date: Fri, 24 Jul 2015 00:30:29 -0700

**Comment by Lymphatus** [comment]
Yes, totally fine and the command you provided is correct but there's a critical bug that affects folder structure.
For example, if you start caesiumclt and the image you want to compress is in the same folder, the command fails with segmentation fault. It works fine if you use the command from a 1 level deeper folder. Consider this structure:
```
|- image.jpg
|- temporary
|- output
``` 
temporary and output are empty folders.

```
$ cd temporary
$ caesiumclt -l -o ../output ../image.jpg
```
Should work. I'm working on the fix right now by the way. Should be up fairly soon.

**Comment by Lymphatus** [comment]
Fix up.
Get the latest release by pulling or cloning again, install again and run the same command. It should work now.

**Comment by satyagvns** [comment]
Hi,
Thanks for your great support to resolve my problem.

Warm Regards,U V N SATYANARAYANA MURTHY,+91 – 872 271 6216.SkypeId : satya_bindu

Date: Fri, 24 Jul 2015 01:03:41 -0700
