### ISSUE TITLE
Not able to install caesiumCLT in Ubuntu 14.04 Machine

### ISSUE THREAD

**Issue by satyagvns** [Lymphatus/CaesiumCLT#3]
Hi,

I am trying to install Caesium in my UBUNTU 14.04 machine. I am getting below errors while installing

Process Followed:
installed "libjpeg-turbo8-dev" before installing CLI Tool

Here is the error output:
root@ip-172-31-7-149:/home/ubuntu/CaesiumCLT# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... none
checking dependency style of gcc... none
checking for  in -ljpeg... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking sys/stats.h usability... no
checking sys/stats.h presence... no
checking for sys/stats.h... no
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking jpeglib.h usability... yes
checking jpeglib.h presence... yes
checking for jpeglib.h... yes
checking for off_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for mkdir... yes
checking for strrchr... yes
checking for strtol... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands
root@ip-172-31-7-149:/home/ubuntu/CaesiumCLT# make
The program 'make' is currently not installed. You can install it by typing:
apt-get install make
root@ip-172-31-7-149:/home/ubuntu/CaesiumCLT# apt-get install make
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  make-doc
The following NEW packages will be installed:
  make
0 upgraded, 1 newly installed, 0 to remove and 123 not upgraded.
Need to get 119 kB of archives.
After this operation, 328 kB of additional disk space will be used.
Get:1 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main make amd64 3.81-8.2ubuntu3 [119 kB]
Fetched 119 kB in 0s (6,932 kB/s)
Selecting previously unselected package make.
(Reading database ... 56741 files and directories currently installed.)
Preparing to unpack .../make_3.81-8.2ubuntu3_amd64.deb ...
Unpacking make (3.81-8.2ubuntu3) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up make (3.81-8.2ubuntu3) ...
root@ip-172-31-7-149:/home/ubuntu/CaesiumCLT# 
root@ip-172-31-7-149:/home/ubuntu/CaesiumCLT# make
Making all in src
make[1]: Entering directory `/home/ubuntu/CaesiumCLT/src'
source='main.c' object='caesiumclt-main.o' libtool=no \
	DEPDIR=.deps depmode=none /bin/bash ../tools/depcomp \
	gcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -c -o caesiumclt-main.o `test -f 'main.c' || echo './'`main.c
source='utils.c' object='caesiumclt-utils.o' libtool=no \
	DEPDIR=.deps depmode=none /bin/bash ../tools/depcomp \
	gcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -c -o caesiumclt-utils.o `test -f 'utils.c' || echo './'`utils.c
utils.c: In function ‘scan_folder’:
utils.c:234:5: warning: implicit declaration of function ‘chdir’ [-Wimplicit-function-declaration]
     chdir(dir);
     ^
utils.c:236:9: warning: implicit declaration of function ‘lstat’ [-Wimplicit-function-declaration]
         lstat(entry->d_name, &statbuf);
         ^
utils.c:258:5: warning: return from incompatible pointer type [enabled by default]
     return *files;
     ^
source='lossless.c' object='caesiumclt-lossless.o' libtool=no \
	DEPDIR=.deps depmode=none /bin/bash ../tools/depcomp \
	gcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -c -o caesiumclt-lossless.o `test -f 'lossless.c' || echo './'`lossless.c
source='compress.c' object='caesiumclt-compress.o' libtool=no \
	DEPDIR=.deps depmode=none /bin/bash ../tools/depcomp \
	gcc -DPACKAGE_NAME=\"caesiumclt\" -DPACKAGE_TARNAME=\"caesiumclt\" -DPACKAGE_VERSION=\"1.9.9\" -DPACKAGE_STRING=\"caesiumclt\ 1.9.9\" -DPACKAGE_BUGREPORT=\"caesium@saerasoft.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"caesiumclt\" -DVERSION=\"1.9.9\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDIO_H=1 -DHAVE_DIRENT_H=1 -DHAVE_JPEGLIB_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MKDIR=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -c -o caesiumclt-compress.o `test -f 'compress.c' || echo './'`compress.c
compress.c: In function ‘cclt_compress’:
compress.c:17:6: warning: variable ‘status’ set but not used [-Wunused-but-set-variable]
  int status;
      ^
compress.c: In function ‘cclt_decompress’:
compress.c:58:9: warning: variable ‘res’ set but not used [-Wunused-but-set-variable]
     int res = 0;
         ^
gcc -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2   -o caesiumclt caesiumclt-main.o caesiumclt-utils.o caesiumclt-lossless.o caesiumclt-compress.o  
caesiumclt-utils.o: In function `jcopy_markers_execute':
/home/ubuntu/CaesiumCLT/src/utils.c:145: undefined reference to `jpeg_write_marker'
caesiumclt-lossless.o: In function `cclt_get_markers':
/home/ubuntu/CaesiumCLT/src/lossless.c:15: undefined reference to `jpeg_std_error'
/home/ubuntu/CaesiumCLT/src/lossless.c:17: undefined reference to `jpeg_CreateDecompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:30: undefined reference to `jpeg_stdio_src'
/home/ubuntu/CaesiumCLT/src/lossless.c:34: undefined reference to `jpeg_save_markers'
/home/ubuntu/CaesiumCLT/src/lossless.c:37: undefined reference to `jpeg_read_header'
caesiumclt-lossless.o: In function `cclt_optimize':
/home/ubuntu/CaesiumCLT/src/lossless.c:60: undefined reference to `jpeg_std_error'
/home/ubuntu/CaesiumCLT/src/lossless.c:61: undefined reference to `jpeg_CreateDecompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:62: undefined reference to `jpeg_std_error'
/home/ubuntu/CaesiumCLT/src/lossless.c:63: undefined reference to `jpeg_CreateCompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:76: undefined reference to `jpeg_stdio_src'
/home/ubuntu/CaesiumCLT/src/lossless.c:86: undefined reference to `jpeg_read_header'
/home/ubuntu/CaesiumCLT/src/lossless.c:89: undefined reference to `jpeg_read_coefficients'
/home/ubuntu/CaesiumCLT/src/lossless.c:93: undefined reference to `jpeg_copy_critical_parameters'
/home/ubuntu/CaesiumCLT/src/lossless.c:113: undefined reference to `jpeg_simple_progression'
/home/ubuntu/CaesiumCLT/src/lossless.c:116: undefined reference to `jpeg_stdio_dest'
/home/ubuntu/CaesiumCLT/src/lossless.c:119: undefined reference to `jpeg_write_coefficients'
/home/ubuntu/CaesiumCLT/src/lossless.c:134: undefined reference to `jpeg_finish_compress'
/home/ubuntu/CaesiumCLT/src/lossless.c:135: undefined reference to `jpeg_destroy_compress'
/home/ubuntu/CaesiumCLT/src/lossless.c:136: undefined reference to `jpeg_finish_decompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:137: undefined reference to `jpeg_destroy_decompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:81: undefined reference to `jpeg_save_markers'
/home/ubuntu/CaesiumCLT/src/lossless.c:129: undefined reference to `jpeg_destroy_decompress'
caesiumclt-compress.o: In function `cclt_compress':
/home/ubuntu/CaesiumCLT/src/compress.c:30: undefined reference to `tjInitCompress'
/home/ubuntu/CaesiumCLT/src/compress.c:32: undefined reference to `tjCompress2'
/home/ubuntu/CaesiumCLT/src/compress.c:48: undefined reference to `tjDestroy'
/home/ubuntu/CaesiumCLT/src/compress.c:49: undefined reference to `tjFree'
caesiumclt-compress.o: In function `cclt_decompress':
/home/ubuntu/CaesiumCLT/src/compress.c:67: undefined reference to `tjAlloc'
/home/ubuntu/CaesiumCLT/src/compress.c:71: undefined reference to `tjInitDecompress'
/home/ubuntu/CaesiumCLT/src/compress.c:72: undefined reference to `tjDecompressHeader2'
/home/ubuntu/CaesiumCLT/src/compress.c:74: undefined reference to `ceil'
/home/ubuntu/CaesiumCLT/src/compress.c:75: undefined reference to `ceil'
/home/ubuntu/CaesiumCLT/src/compress.c:82: undefined reference to `tjAlloc'
/home/ubuntu/CaesiumCLT/src/compress.c:84: undefined reference to `tjDecompress2'
/home/ubuntu/CaesiumCLT/src/compress.c:94: undefined reference to `tjDestroy'
collect2: error: ld returned 1 exit status
make[1]: *** [caesiumclt] Error 1
make[1]: Leaving directory `/home/ubuntu/CaesiumCLT/src'
make: *** [all-recursive] Error 1
root@ip-172-31-7-149:/home/ubuntu/CaesiumCLT# make install
Making install in src
make[1]: Entering directory `/home/ubuntu/CaesiumCLT/src'
gcc -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2   -o caesiumclt caesiumclt-main.o caesiumclt-utils.o caesiumclt-lossless.o caesiumclt-compress.o  
caesiumclt-utils.o: In function `jcopy_markers_execute':
/home/ubuntu/CaesiumCLT/src/utils.c:145: undefined reference to `jpeg_write_marker'
caesiumclt-lossless.o: In function `cclt_get_markers':
/home/ubuntu/CaesiumCLT/src/lossless.c:15: undefined reference to `jpeg_std_error'
/home/ubuntu/CaesiumCLT/src/lossless.c:17: undefined reference to `jpeg_CreateDecompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:30: undefined reference to `jpeg_stdio_src'
/home/ubuntu/CaesiumCLT/src/lossless.c:34: undefined reference to `jpeg_save_markers'
/home/ubuntu/CaesiumCLT/src/lossless.c:37: undefined reference to `jpeg_read_header'
caesiumclt-lossless.o: In function `cclt_optimize':
/home/ubuntu/CaesiumCLT/src/lossless.c:60: undefined reference to `jpeg_std_error'
/home/ubuntu/CaesiumCLT/src/lossless.c:61: undefined reference to `jpeg_CreateDecompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:62: undefined reference to `jpeg_std_error'
/home/ubuntu/CaesiumCLT/src/lossless.c:63: undefined reference to `jpeg_CreateCompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:76: undefined reference to `jpeg_stdio_src'
/home/ubuntu/CaesiumCLT/src/lossless.c:86: undefined reference to `jpeg_read_header'
/home/ubuntu/CaesiumCLT/src/lossless.c:89: undefined reference to `jpeg_read_coefficients'
/home/ubuntu/CaesiumCLT/src/lossless.c:93: undefined reference to `jpeg_copy_critical_parameters'
/home/ubuntu/CaesiumCLT/src/lossless.c:113: undefined reference to `jpeg_simple_progression'
/home/ubuntu/CaesiumCLT/src/lossless.c:116: undefined reference to `jpeg_stdio_dest'
/home/ubuntu/CaesiumCLT/src/lossless.c:119: undefined reference to `jpeg_write_coefficients'
/home/ubuntu/CaesiumCLT/src/lossless.c:134: undefined reference to `jpeg_finish_compress'
/home/ubuntu/CaesiumCLT/src/lossless.c:135: undefined reference to `jpeg_destroy_compress'
/home/ubuntu/CaesiumCLT/src/lossless.c:136: undefined reference to `jpeg_finish_decompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:137: undefined reference to `jpeg_destroy_decompress'
/home/ubuntu/CaesiumCLT/src/lossless.c:81: undefined reference to `jpeg_save_markers'
/home/ubuntu/CaesiumCLT/src/lossless.c:129: undefined reference to `jpeg_destroy_decompress'
caesiumclt-compress.o: In function `cclt_compress':
/home/ubuntu/CaesiumCLT/src/compress.c:30: undefined reference to `tjInitCompress'
/home/ubuntu/CaesiumCLT/src/compress.c:32: undefined reference to `tjCompress2'
/home/ubuntu/CaesiumCLT/src/compress.c:48: undefined reference to `tjDestroy'
/home/ubuntu/CaesiumCLT/src/compress.c:49: undefined reference to `tjFree'
caesiumclt-compress.o: In function `cclt_decompress':
/home/ubuntu/CaesiumCLT/src/compress.c:67: undefined reference to `tjAlloc'
/home/ubuntu/CaesiumCLT/src/compress.c:71: undefined reference to `tjInitDecompress'
/home/ubuntu/CaesiumCLT/src/compress.c:72: undefined reference to `tjDecompressHeader2'
/home/ubuntu/CaesiumCLT/src/compress.c:74: undefined reference to `ceil'
/home/ubuntu/CaesiumCLT/src/compress.c:75: undefined reference to `ceil'
/home/ubuntu/CaesiumCLT/src/compress.c:82: undefined reference to `tjAlloc'
/home/ubuntu/CaesiumCLT/src/compress.c:84: undefined reference to `tjDecompress2'
/home/ubuntu/CaesiumCLT/src/compress.c:94: undefined reference to `tjDestroy'
collect2: error: ld returned 1 exit status
make[1]: *** [caesiumclt] Error 1
make[1]: Leaving directory `/home/ubuntu/CaesiumCLT/src'
make: *** [install-recursive] Error 1
root@ip-172-31-7-149:/home/ubuntu/CaesiumCLT# whereis caesiumclt
caesiumclt:

**Comment by Lymphatus** [comment]
The problem is in this line
```
gcc -Wall -D_FILE_OFFSET_BITS=64 -ljpeg -lturbojpeg -lm -std=c99 -g -O2 -o caesiumclt caesiumclt-main.o caesiumclt-utils.o caesiumclt-lossless.o caesiumclt-compress.o caesiumclt-utils.o
```

When compiling the *.o files, the needed libraries should be placed at the end of the line, not before the object files.
Thus the correct line should be
```
gcc -Wall -D_FILE_OFFSET_BITS=64 -std=c99 -g -O2 -o caesiumclt caesiumclt-main.o caesiumclt-utils.o caesiumclt-lossless.o caesiumclt-compress.o caesiumclt-utils.o -ljpeg -lturbojpeg -lm
```
[Details on this issue here.](http://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc)

Also I'm noticing you are not compiling the latest version. Use ```git pull``` to sync with the latest version.
